GET http://localhost:3000/cliente
content-type: application/json

###
GET http://localhost:3000/cliente/1
content-type: application/json

################################Paciente#############################
####
GET http://localhost:3000/paciente/pacientes
content-type: application/json

####
GET http://localhost:3000/pacientes/1
content-type: application/json

###
POST  http://localhost:3000/pacientes
content-type: application/json

  {
      "prontuario": "1010",
      "cpf": "24224224224",
      "cns": "123456789",
      "nome": "ANDRE BALDE DA SILVA SAURO",
      "nomeSocial": "BALDINHO",
      "dataNascimento": "02/07/1974",
      "mae": "NAO SEI O NOME",
      "telefone":"85992312094",
      "celular": "85992312094",
      "email":"balde.mais@gmail.com"
  }
###
PUT  http://localhost:3000/pacientes/4
content-type: application/json

  {
      "prontuario": "1010",
      "cpf": "24224224224",
      "cns": "123456789",
      "nome": "ANDRE BALDE DA SILVA SAURO",
      "nomeSocial": "BALDINHO",
      "dataNascimento": "02/07/1974",
      "mae": "NAO SEI O NOME",
      "telefone":"85992312094",
      "celular": "85992312094",
      "email":"balde.mais.balde@gmail.com"
  }


################################Risco#############################
####
GET http://localhost:3000/risco/recepcao
content-type: application/json


################################Medico#############################
####
GET http://localhost:3000/medico/recepcao
content-type: application/json
